'use client';

import { SEOReport } from '../types';
import { ScoreGauge } from './ScoreGauge';
import { MetaTagsSection } from './sections/MetaTagsSection';
import { HeadingsSection } from './sections/HeadingsSection';
import { ImagesSection } from './sections/ImagesSection';
import { LinksSection } from './sections/LinksSection';
import { ContentSection } from './sections/ContentSection';
import { RecommendationsSection } from './sections/RecommendationsSection';
import { SecuritySection } from './sections/SecuritySection';
import { PDFExportButton } from './PDFExportButton';

interface Props {
  report: SEOReport;
  onReset: () => void;
}

export function ReportDashboard({ report, onReset }: Props) {
  return (
    <div className="space-y-8">
      {/* Report Header */}
      <div className="bg-white rounded-xl shadow-sm border p-6">
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <div>
            <h2 className="text-2xl font-bold text-gray-900">SEO Report</h2>
            <p className="text-gray-500 mt-1">{report.url}</p>
            <p className="text-sm text-gray-400 mt-1">Analyzed: {report.analyzed_at}</p>
          </div>
          <div className="flex items-center gap-4">
            <ScoreGauge score={report.score} />
            <PDFExportButton report={report} />
          </div>
        </div>
      </div>

      {/* Recommendations First */}
      <RecommendationsSection recommendations={report.recommendations} />

      {/* Grid Layout for Details */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <MetaTagsSection meta={report.meta_tags} />
        <HeadingsSection headings={report.headings} />
        <ImagesSection images={report.images} />
        <LinksSection links={report.links} />
        <ContentSection content={report.content} />
        <SecuritySection security={report.security} performance={report.performance} />
      </div>

      {/* Brand Footer on Report */}
      <div className="text-center py-8 border-t">
        <p className="text-gray-500">
          Report generated by <span className="font-semibold text-blue-600">ScaleWithDestiny</span>
        </p>
        <p className="text-sm text-gray-400 mt-1">analyser.scalewithdestiny.com</p>
      </div>

      <button
        onClick={onReset}
        className="w-full py-3 border-2 border-blue-600 text-blue-600 font-semibold rounded-lg hover:bg-blue-50"
      >
        Analyze Another Site
      </button>
    </div>
  );
}